uses: mr-smithers-excellent/docker-build-push@v4
with:
  image: khaledalmana/personal
  tag: latest
  registry: docker.io
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}